linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - ifshort
    - lll
    - nlreturn
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - noctx

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
