language: go

go:
  - stable

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - dep ensure

script:
  - make lint
  - make test
  - make
