name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Test
        run: make test

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
